
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.6.4</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

  </PropertyGroup>
  <ItemGroup>
    <None Update="devlog.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GnomeStack.Secrets.OperatingSystem" Version="0.1.6" />
    <PackageReference Include="NCalc" Version="7.0.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>

</Project>
